# Generated by Django 6.1 on 2026-08-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
