# Generated by Django 6.1 on 2026-08-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_full_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orders_count',
        ),
        migrations.AlterField(
            model_name='order',
            name='full_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
