# Generated by Django 6.1 on 2026-08-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Product image')),
                ('name', models.CharField(verbose_name="Product's name")),
                ('about', models.TextField(verbose_name="Product's about")),
                ('price', models.CharField(verbose_name="Product's price")),
                ('weight', models.CharField(blank=True, verbose_name="Products's weight (in Gram)")),
                ('height', models.CharField(blank=True, verbose_name="Products's height (in CentiMetre)")),
                ('width', models.CharField(blank=True, verbose_name="Products's width (in CentiMetre)")),
                ('special', models.BooleanField(default=False, verbose_name='Is this product special?')),
                ('warranty', models.CharField(blank=True, verbose_name="Product's warranty")),
                ('date', models.DateField(auto_now_add=True)),
                ('buys', models.PositiveIntegerField(default=0, verbose_name="Product's buy counter")),
                ('slug', models.SlugField(verbose_name="Product's link")),
            ],
        ),
    ]
